package Model.Item_package;

public enum UsableActivationTime {
    GAME_START, ON_ATTACK, OUR_RANGED_OR_HYBRID_HERO_ON_ATTACK, ENEMY_HERO_IS_RANGED_OR_HYBRID, ON_SPAWN_A_MINION,
    OUR_HORO_ON_ATTACK, DEATH_OF_OUR_Minion
}
