package Model.Card_package.minion_special_power;

public enum MinionSpecialPowerTarget {
    HITED_ENEMY, HITED_MINION, MINIONS_IN_NEIGHBOR, UNTIL_2_DISTANCE_MINIONS, MINION_AND_OUR_MINION_IN_NEIGHBOR, RANDOM_ENEMY_MINION, HIMSELF,
    RANDOM_ENEMY_FORCE_IN_NEIGHBOR, ALL_OUR_MINION, ENEMY_MINIONS_IN_NEIGHBOR, ENEMY_HERO

}
